### ISSUE TITLE
Can't fully read the title of Bets or scopes

### ISSUE THREAD

**Issue by Amzani** [shapeitapp/shapeitapp#13]
<img width="1641" alt="Screenshot 2023-06-22 at 09 19 01" src="https://github.com/shapeitapp/shapeitapp/assets/554438/8bb777ef-142c-455a-8aeb-c5a69f9a2153">

**Comment by fmvilas** [comment]
If you hover over the text, you should see the full title. Isn't it enough?

**Comment by Amzani** [comment]
I find it not intuitive as you have to figure out that you need to hover first.

**Comment by fmvilas** [comment]
How we could solve this? Maybe making the limit a bit larger and use 2 columns instead of 3?

**Comment by Amzani** [comment]
@fmvilas 
My proposal is to take a minimalist UI approach especially for the MVP.
  
- Display the full Bet title
- Get rid of scopes in the column as we already have them in the middle.
- Add a title `Scopes` bellow hillchart.

<img width="1401" alt="Screenshot 2023-06-27 at 20 04 04" src="https://github.com/shapeitapp/shapeitapp/assets/554438/0324ebab-e26d-4694-a01d-6bebd6997e39">

wdyt ?

**Comment by fmvilas** [comment]
Sounds good. I won't add the title Scopes below the hill chart though because the hill chart itself is showing the scopes too. The links below the hill chart work more like a legend. I'm actually questioning if we should have that legend at all. It was there because initially the dots on the chart weren't clickable but now they are.
